### ISSUE TITLE
该固件是不是对RTL88X2BU系列的USB无线网卡支持不好？（R4S）

### ISSUE THREAD

**Issue by McflyWZX** [DHDAXCW/NanoPi-R4S#146]
我看软件包里有kmod-rtl88x2bu，但是我插上USB3.0的无线网卡（RTL8812BU），电脑显示是WI-FI 4（802.11n）协议，只有300M.然鹅在路由器管理界面我是设置了频率模式为AC的，不知道为何没有生效

**Comment by Fbug1** [comment]
好像openwrt对螃蟹的USB无线网卡的支持都挺不好的，我有8812BU和8811CU，这两张卡在我的R4S上都是时好时坏，有时可以用有时能识别但不能正常工作而且不能同时设置2.4g和5g的ap
我现在在用雷凌rt3575，openwrt对雷凌的芯片支持的挺不错

**Comment by McflyWZX** [comment]
> 好像openwrt对螃蟹的USB无线网卡的支持都挺不好的，我有8812BU和8811CU，这两张卡在我的R4S上都是时好时坏，有时可以用有时能识别但不能正常工作而且不能同时设置2.4g和5g的ap 我现在在用雷凌rt3575，openwrt对雷凌的芯片支持的挺不错

后来想了想还是 路由 -> 交换机 -> 无线AP/PC   比较好
