### ISSUE TITLE
我只能说牛蛙

### ISSUE THREAD

**Issue by QTFIUE** [DHDAXCW/NanoPi-R4S#148]
![image](https://user-images.githubusercontent.com/95908233/147567089-d002ae3a-a43e-4430-a717-fc29e110960f.png)
对不起，碍你们眼了，我强迫他们打钱给我了

**Comment by QTFIUE** [comment]
![image](https://user-images.githubusercontent.com/95908233/147567411-72c62ff7-d341-4fde-bbb1-398218eaf0d1.png)

**Comment by DHDAXCW** [comment]
？

**Comment by QTFIUE** [comment]
问号啥？我说错了？

**Comment by lone-wind** [comment]
有一说一，自从移除某把收费解决问题一直挂在嘴上的人，群里又恢复成了往日和谐友爱、吹水打屁的快乐状态

**Comment by QTFIUE** [comment]
好家伙，阴阳人来了是吧，属于是强迫你给钱了，是不是想白嫖不让白嫖不开心？？

**Comment by QTFIUE** [comment]
难道不是提供了解决方案么？还是嫉妒了

**Comment by lone-wind** [comment]
在issue下说来说去也蛮没意思的。祝你加更多的op群，遇到更多接受“收费解决问题”的求助者。拜拜

**Comment by QTFIUE** [comment]
那确实，人家op官方群也没说啥，就你们这屁事多，估计群里举报的都是一群那啥，白嫖不了气急败坏

**Comment by QTFIUE** [comment]
没别的事可以关闭issue了，确实没啥意思哈，笑死了
