### ISSUE TITLE
有对应的kmod吗？

### ISSUE THREAD

**Issue by wenyuanyu** [DHDAXCW/NanoPi-R4S#149]
能下到对应的kmod吗？需要kmod-bonding

**Comment by DHDAXCW** [comment]
这是什么东西？、

**Comment by wenyuanyu** [comment]
kernel模块，比如kmod-bonding要和kernel的版本完全一致，比如5.10.88-1-246b90ea16aa83615004e60b3168c968这种

**Comment by wenyuanyu** [comment]
刷了snapshot的版本自己慢慢配吧😂
