### ISSUE TITLE
WAN接口速率问题

### ISSUE THREAD

**Issue by younasiqw** [DHDAXCW/NanoPi-R4S#150]
有时候1G全双工会自动变成100M全双工，重启有时候无效，就很奇怪电脑接口都是支持1G全双工的

**Comment by RESHADOW-J** [comment]
同样有这样的问题，R4S 4G版，尝试过多个版本和不同作者的固件，都出现过重启后1G全双工的WAN口速率掉至100M，感觉像是网口驱动的问题
