### ISSUE TITLE
易有云、可道云访问外挂硬盘含有一些文件的目录就会导致系统重启

### ISSUE THREAD

**Issue by aotsukiqx** [DHDAXCW/NanoPi-R4S#151]
易有云、可道云访问外挂硬盘含有一些文件的目录就会导致系统重启。仅猜测，因为不管是readlog还是luci的日志、都来不及看到任何输出，web和ssh都会瞬间停止响应，且关掉易有云后过段时间就可以重新登录web界面，但是看开机时间能看出来系统已经重启。
试过docker版、正式版和稳定版都会如此

**Comment by DHDAXCW** [comment]
已联系开发组

**Comment by DHDAXCW** [comment]
这个是内核的文件系统有问题，硬盘重新格式化为ext4就好了

**Comment by DHDAXCW** [comment]
具体啥得看内核日志

**Comment by aotsukiqx** [comment]
内核日志看不到，比较惨
