### ISSUE TITLE
版本号能不能稍微精简下？

### ISSUE THREAD

**Issue by halloketty** [DHDAXCW/NanoPi-R4S#153]
![屏幕截图 2022-01-02 123415](https://user-images.githubusercontent.com/83857799/147866336-b0092e6b-b753-4abc-8aa6-1a5495513dd4.png)
以生成日期作为版本号的话，这里略显重复，导致末尾换行，第三行单单一个数字很不好看，建议保留一个即可。
另外，系统状态里的 Telegram | 电报交流群 可以可以考虑去掉。
以上仅从页面美观角度考虑，供作者参考。

**Comment by DHDAXCW** [comment]
安排
