### ISSUE TITLE
请完善USB无线网卡的问题。

### ISSUE THREAD

**Issue by bg2vcj** [DHDAXCW/NanoPi-R4S#155]
首先感谢作者编译这么好的固件。
在使用中发现 USB无线网卡有一些问题，希望作者能完善它。
我使用网件的A6210 USB无线WiFi网卡，遇到几个问题
1·网卡插入usb后经常不能识别，需要在网卡的高级设置里 点802.11 b 支持或者不支持 来刷新网卡的状态。才能识别usb网卡。
（希望可以增加刷新网卡状态的按钮，或者自动刷新识别网卡）
2·例如usb 1口插入无线网卡，在挪到usb 2口 ，1口的无线网卡 不能删除。没有删除按钮。
（希望增加删除按钮）
3·在系统管理里 没有 系统初始化按钮（想初始化 只能刷卡）
（希望增加系统初始化按钮）
如果您看到这条留言，请修改这些问题，谢谢

**Comment by DHDAXCW** [comment]
是的 写死在配置里了，但是不影响 能用就行
