### ISSUE TITLE
千兆带宽进行测试会导致系统崩溃重启

### ISSUE THREAD

**Issue by jounace** [DHDAXCW/NanoPi-R4S#164]
20220118 用speedtest 和 steam下载进行测试，当千兆带宽跑满时系统会崩溃重启

**Comment by DHDAXCW** [comment]
有提供日志吗？或者去群里私我

**Comment by jounace** [comment]
dalao 想问下重启发生后在哪可以找到相应的系统日志

**Comment by DHDAXCW** [comment]
刷最新固件吧，顺便带内核日志  系统--内核日志
