### ISSUE TITLE
R4S 如何正确关机 ？

### ISSUE THREAD

**Issue by L-Meteor** [DHDAXCW/NanoPi-R4S#170]
大佬，像您求教一下，请问您编译的 R4S 固件中是否包含关机的选项 ？若是直接关闭电源 ，是否会对 R4S 造成损坏或是配置的丢失？谢谢！

**Comment by hosence** [comment]
没记错的话，1.18之后的固件有关机选项

**Comment by idviidvi** [comment]
进终端，输入poweroff

**Comment by showme2005** [comment]
想定时关机的话..自己在计划任务 里面加命令  0 0 0 * * * poweroff  前面的时间自己去改~
