### ISSUE TITLE
docker ext4 版本镜像不可用

### ISSUE THREAD

**Issue by TianhaoC** [DHDAXCW/NanoPi-R4S#178]
尝试过各种低格工具，以确保无数据残留
并尝试过多张不同厂商的sd卡
均出现 sys灯亮 系统启动成功，LAN WAN灯不亮的情况
前后刷过20-30次，均失败
尝试够其他大佬的docker ext4版本镜像一次成功
可以确认是本仓库中镜像的问题

**Comment by hosence** [comment]
我也遇到了和你同样的问题，无法启动

**Comment by TianhaoC** [comment]
[2022.03.06 NanoPi-R4S Plus_Docker容器版_全插件](https://github.com/DHDAXCW/NanoPi-R4S/releases/tag/2022.03.06-Lean1)

升级内核后的版本，可以啦，一次成功，nice
