### ISSUE TITLE
smartdns 是不是新固件里都没有了?

### ISSUE THREAD

**Issue by ericghost** [DHDAXCW/NanoPi-R4S#193]
smartdns 新固件都没有了, 而且内核都降到5.4了

**Comment by quango-web** [comment]
可能老大要测试什么暂时取消了吧，不过还是强烈希望保留的。
3.29版本卡刷在R4S首次启动时ip分配好像有点问题，sys灯闪灯灭，电脑右下角网络图标显示断开好几次

**Comment by ericghost** [comment]
> 

我是TTYD在线升级的,倒是没有ip分配问题,家里设备都一切正常

**Comment by ericghost** [comment]
我还是刷回了3.18那个固件 感觉那个还是比较稳定的
