### ISSUE TITLE
通过TTYD终端在线升级，无最新版本，只能找到多天前的版本？

### ISSUE THREAD

**Issue by reallwp** [DHDAXCW/NanoPi-R4S#200]
通过TTYD终端在线升级，无当天的最新版本，只能找到多天前的版本？

**Comment by Fetiz** [comment]
刚刚测试更新脚本，直接提示无法找到固件
<img width="222" alt="image" src="https://user-images.githubusercontent.com/20578132/161384233-a55f5098-a180-462a-836b-382cf69ba38e.png">

**Comment by reallwp** [comment]
> 刚刚测试更新脚本，直接提示无法找到固件 <img alt="image" width="222" src="https://user-images.githubusercontent.com/20578132/161384233-a55f5098-a180-462a-836b-382cf69ba38e.png">

你发完我刚试，我可以找到固件，但还是不能找到当天的版本
![Snipaste_2022-04-02_21-00-13](https://user-images.githubusercontent.com/61379288/161384580-2137ab27-5086-4536-89f1-c29d7806f72a.png)
![Snipaste_2022-04-02_21-01-03](https://user-images.githubusercontent.com/61379288/161384583-b296aba0-168c-4237-a7ed-fbbff4585c8d.png)

**Comment by Fetiz** [comment]
> > 刚刚测试更新脚本，直接提示无法找到固件 <img alt="image" width="222" src="https://user-images.githubusercontent.com/20578132/161384233-a55f5098-a180-462a-836b-382cf69ba38e.png">
> 
> 
> 
> 你发完我刚试，我可以找到固件，但还是不能找到当天的版本
> 
> ![Snipaste_2022-04-02_21-00-13](https://user-images.githubusercontent.com/61379288/161384580-2137ab27-5086-4536-89f1-c29d7806f72a.png)
> 
> ![Snipaste_2022-04-02_21-01-03](https://user-images.githubusercontent.com/61379288/161384583-b296aba0-168c-4237-a7ed-fbbff4585c8d.png)
> 
> 
> 
> 

去看了眼release 发现这几天的release 都没有生成固件 全是源码。估计是这个原因

**Comment by DHDAXCW** [comment]
今天版本编译有点问题，全改明天出包

**Comment by reallwp** [comment]
> 今天版本编译有点问题，全改明天出包

谢谢大佬

**Comment by ericghost** [comment]
感觉还是3.18这个用着最稳定,目前对我来说

**Comment by reallwp** [comment]
> 感觉还是3.18这个用着最稳定,目前对我来说

大佬把3.18后的都删了🥶

**Comment by ericghost** [comment]
> 
哈哈,刚发现,后面几天的固件我都刷了, 插件不全,而且还有点bug,估计就是编译的问题吧, 也就18号这个还行反正用着没啥问题
