### ISSUE TITLE
4.4的固件内核还是5.4?

### ISSUE THREAD

**Issue by ericghost** [DHDAXCW/NanoPi-R4S#202]
内核没有考虑升级到5.15吗? 依然还是没有smartdns插件?

**Comment by DHDAXCW** [comment]
smartdns这个要等固件稳定了再加，内核问题暂时不更新到5.15  因为无线需要得

**Comment by ericghost** [comment]
> smartdns这个要等固件稳定了再加，内核问题暂时不更新到5.15 因为无线需要得

欧克
