### ISSUE TITLE
编译请教一下

### ISSUE THREAD

**Issue by Lu-Lucifer** [DHDAXCW/NanoPi-R4S#227]
如果要编译R5S的固件的话，大概要改哪些内容呢

**Comment by DHDAXCW** [comment]
自己适配，我看不上r5s

**Comment by Lu-Lucifer** [comment]
@DHDAXCW 可以指个方向嘛

**Comment by ss-v2ray** [comment]
自行适配

**Comment by DHDAXCW** [comment]
> @DHDAXCW 可以指个方向嘛

openwrt用5.15内核做一个dts，然后uboot要升级到2022.04版，自己弄个ATF本地打包脚本。就这么简单。
