### ISSUE TITLE
R4S正式版断网，断电重启后发现系统自动重置了

### ISSUE THREAD

**Issue by ydnm** [DHDAXCW/NanoPi-R4S#238]
各位大佬们，早上起来发现机器开着但是断网了，断电重启R4S后发现系统自动重置了，跟刚刷的固件一样，啥配置都没了。原来我将r4s的lan口地址改成192.168.2.1，自动重置r4s变回192.168.11.1后，原来的192.168.2.1指向了光猫，192.168.1.1也是光猫，这点也很奇怪，现在这2个ip都指向光猫了。
之前开迅雷bt下载的时候也经常断网，但那个可能是光猫的问题，wan口down了，重启r4s没用要光猫也重启才恢复
用的是5月份的某个正式版固件，开着ssr+和smartdns，电信光猫路由模式开了dmz虚拟主机到r4s。

ps: 请问光猫怎么把管理禁了不让电信改参数，然后会对宽带有什么影响吗

**Comment by DHDAXCW** [comment]
上doornet2解愁

**Comment by ydnm** [comment]
> 上doornet2解愁

好吧谢谢大佬~ 我先换tf卡再试下，原来的tf卡貌似已经废了
