### ISSUE TITLE
6.21版开始无法关闭sfe加速

### ISSUE THREAD

**Issue by Xlyaon** [DHDAXCW/NanoPi-R4S#240]
版本为稳定版
同时6.15稳定版本adguardhome无法正常启动，下载核心报错
awk: /etc/config/AdGuardHome.yaml: No such file or directory
AdGuardHome service disabled
Command failed: Not found
rm: '/usr/bin/AdGuardHome' is a directory
awk: /etc/config/AdGuardHome.yaml: No such file or directory

**Comment by coolhugh** [comment]
重启就好了
